In [219]:
import pandas as pd

In [220]:
sleep_data = pd.read_csv('/Users/dashkwan/Desktop/Programming/sleep_whoop/Sleep_health_and_lifestyle_dataset.csv')
sleep_data.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

## Data Cleaning

In [221]:
sleep_data.drop(columns='Occupation')

,Person ID,Gender,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [222]:
fair_sleep = sleep_data[sleep_data['Quality of Sleep'] >= 7]
poor_sleep = sleep_data[sleep_data['Quality of Sleep'] < 7]
print(f'fair sleep: {len(fair_sleep)}')
print(f'poor sleep: {len(poor_sleep)}')

fair sleep: 257
poor sleep: 117

In [223]:
print(sleep_data.shape)
print(sleep_data.isna().sum())

(374, 13)
Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [224]:
sleep_data['Blood Pressure'].str.split('/')

0      [126, 83]
1      [125, 80]
2      [125, 80]
3      [140, 90]
4      [140, 90]
         ...
369    [140, 95]
370    [140, 95]
371    [140, 95]
372    [140, 95]
373    [140, 95]
Name: Blood Pressure, Length: 374, dtype: object

In [225]:
sleep_data[['Systolic', 'Diastolic']] = sleep_data['Blood Pressure'].str.split('/', expand=True).astype(float)
sleep_data = sleep_data.drop(columns='Blood Pressure')
sleep_data.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder,Systolic,Diastolic
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,77,4200,NaN,126.0,83.0
1,2,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,NaN,125.0,80.0
2,3,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,NaN,125.0,80.0
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140.0,90.0
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140.0,90.0

In [226]:
sleep_data['BMI Category'].unique()

<StringArray>
['Overweight', 'Normal', 'Obese', 'Normal Weight']
Length: 4, dtype: str

In [227]:
sleep_data['BMI Category'] = sleep_data['BMI Category'].map({'Normal': 1, 'Normal Weight': 1, 'Overweight': 2, 'Obese': 3})
sleep_data.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Sleep Disorder,Systolic,Diastolic
0,1,Male,27,Software Engineer,6.1,6,42,6,2,77,4200,NaN,126.0,83.0
1,2,Male,28,Doctor,6.2,6,60,8,1,75,10000,NaN,125.0,80.0
2,3,Male,28,Doctor,6.2,6,60,8,1,75,10000,NaN,125.0,80.0
3,4,Male,28,Sales Representative,5.9,4,30,8,3,85,3000,Sleep Apnea,140.0,90.0
4,5,Male,28,Sales Representative,5.9,4,30,8,3,85,3000,Sleep Apnea,140.0,90.0

In [228]:
sleep_data['Quality of Sleep'] = sleep_data['Quality of Sleep'].astype(float)
sleep_data['Quality of Sleep'] = sleep_data['Quality of Sleep'].map(lambda x: 'Good' if x >= 7 else "Poor")
sleep_data = sleep_data.drop(columns=['Person ID', 'Sleep Disorder'])
sleep_data

,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps,Systolic,Diastolic
0,Male,27,Software Engineer,6.1,Poor,42,6,2,77,4200,126.0,83.0
1,Male,28,Doctor,6.2,Poor,60,8,1,75,10000,125.0,80.0
2,Male,28,Doctor,6.2,Poor,60,8,1,75,10000,125.0,80.0
3,Male,28,Sales Representative,5.9,Poor,30,8,3,85,3000,140.0,90.0
4,Male,28,Sales Representative,5.9,Poor,30,8,3,85,3000,140.0,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...
369,Female,59,Nurse,8.1,Good,75,3,2,68,7000,140.0,95.0
370,Female,59,Nurse,8.0,Good,75,3,2,68,7000,140.0,95.0
371,Female,59,Nurse,8.1,Good,75,3,2,68,7000,140.0,95.0
372,Female,59,Nurse,8.1,Good,75,3,2,68,7000,140.0,95.0
373,Female,59,Nurse,8.1,Good,75,3,2,68,7000,140.0,95.0

In [229]:
sleep_data = sleep_data.drop_duplicates()
sleep_data.shape  # confirm you're down to ~109 rows

(109, 12)

## Defining Targets

X = features
y = target

In [230]:
features = ['Sleep Duration', 'Physical Activity Level', 'Stress Level', 
            'BMI Category', 'Heart Rate', 'Daily Steps', 'Age', 'Systolic', 'Diastolic']

X = sleep_data[features]
y = sleep_data['Quality of Sleep']

X.dtypes

Sleep Duration             float64
Physical Activity Level      int64
Stress Level                 int64
BMI Category                 int64
Heart Rate                   int64
Daily Steps                  int64
Age                          int64
Systolic                   float64
Diastolic                  float64
dtype: object

In [231]:
y.value_counts()

Quality of Sleep
Good    73
Poor    36
Name: count, dtype: int64

## Train/Test Split

- Using stratify=y because of the imbalance between Sleep Quality labels
- Also using test_size = 0.2 (20%) as a standard

In [232]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

Saving 80% of data for X_train and y_train and 20% for X_test and y_test

Sanity Check

In [233]:
y_train.value_counts(normalize=True)

Quality of Sleep
Good    0.666667
Poor    0.333333
Name: proportion, dtype: float64

In [234]:
y_test.value_counts(normalize=True)

Quality of Sleep
Good    0.681818
Poor    0.318182
Name: proportion, dtype: float64

## Building The Pipeline

In [235]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

log_reg_pipeline = make_pipeline(
    StandardScaler(),
    LogisticRegression()
)

Right now, log_reg_pipeline is just a definition. When we call X_train, y_train on it, it will 
- Take X_train, fit the StandardScaler on it (compute each feature's mean and standard deviation from the training data), and transform X_train into scaled values
- Take that scaled version of X_train and feed it into LogisticRegression().fit() along with y_train

Without a pipeline, the approach is to scale the entire dataset once before splitting into train/test (which is wrong). That's a subtle bug: the scaler would compute mean/std using information from the test set too, meaning your "unseen" test data quietly influenced how the training data got transformed. 

Pipelines force the correct order - fit the scaler only on training data, then when we call it on the test data it reuses the training set's mean/std. 

Bottom line: **the model should never learn anything, even indirectly, from data it's supposed to be evaluated on.**

In [236]:
log_reg_pipeline.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [237]:
log_reg_pipeline.score(X_test, y_test)

0.9545454545454546

In [239]:
y_test.value_counts()

Quality of Sleep
Good    15
Poor     7
Name: count, dtype: int64

In [240]:
print(log_reg_pipeline)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [241]:
print(log_reg_pipeline.named_steps['logisticregression'].coef_)
print(log_reg_pipeline.named_steps['logisticregression'].intercept_)

[[-2.02934276 -0.30812533  1.73170346  0.09868165  0.54283708  0.3084046
  -0.97032756  0.38672884  0.3163679 ]]
[-2.48559911]

In [242]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(log_reg_pipeline, X, y, cv=5, scoring='accuracy')
print(scores, scores.mean())

[1.         1.         1.         0.77272727 1.        ] 0.9545454545454545

4 perfect folds, 1 dropped to 77%

In [243]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred = log_reg_pipeline.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[15  0]
 [ 1  6]]
              precision    recall  f1-score   support

        Good       0.94      1.00      0.97        15
        Poor       1.00      0.86      0.92         7

    accuracy                           0.95        22
   macro avg       0.97      0.93      0.95        22
weighted avg       0.96      0.95      0.95        22

For the 15, 0 and 1,6:
all 15 "Good" cases were correctly predicted as Good (no false positives). Of 7 "Poor" cases, 6 were caught correctly and 1 was missed — predicted as Good when it was actually Poor. 

Recall on "Poor" is 0.86 — lower than everything else — which is the number that captures this directly. Worth a line in your writeup: "the model's weakest point is catching poor sleep cases; missing one recall point matters more here than a missed 'Good' case would."

### GridSearchCV

Evaluating each combination of hyperparameter values and returning which one ran best

In [244]:
from sklearn.model_selection import GridSearchCV

param_grid = {'logisticregression__C': [0.01, 0.1, 1, 10, 100]}

grid_search = GridSearchCV(log_reg_pipeline, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

print(grid_search.best_params_)
print(grid_search.best_score_)

{'logisticregression__C': 1}
0.9882352941176471

C=1 is the default: the default hyperparameter was already close to optimal for this data. For writeup: "tested C values from 0.01 to 100 via GridSearchCV; the default (C=1) was already optimal, suggesting the classes are cleanly separable enough that regularization strength isn't the limiting factor here."

In [245]:
final_log_reg = grid_search.best_estimator_
final_score = final_log_reg.score(X_test, y_test)
print(final_score)

0.9545454545454546